# Generated by Django 6.0.1 on 2026-01-24 16:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('meta_bronze', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('meta_prata', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('meta_ouro', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_periodo', models.CharField(max_length=50)),
                ('bronze', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prata', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ouro', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValorDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='metas.analista')),
            ],
        ),
    ]
