# Generated by Django 6.0.1 on 2026-01-24 16:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrecadacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='NivelMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_periodo', models.CharField(help_text='Ex: Janeiro 2026', max_length=50)),
                ('valor_bronze', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_prata', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_ouro', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.DeleteModel(
            name='MetaEmpresa',
        ),
        migrations.RemoveField(
            model_name='analista',
            name='meta_bronze',
        ),
        migrations.RemoveField(
            model_name='analista',
            name='meta_ouro',
        ),
        migrations.RemoveField(
            model_name='analista',
            name='meta_prata',
        ),
        migrations.AddField(
            model_name='analista',
            name='empresa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arrecadacaodiaria',
            name='analista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrecadacoes', to='metas.analista'),
        ),
        migrations.AddField(
            model_name='analista',
            name='metas_referencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='metas.nivelmeta'),
        ),
        migrations.DeleteModel(
            name='ValorDiario',
        ),
    ]
