# Generated by Django 6.0.1 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0002_arrecadacaodiaria_nivelmeta_delete_metaempresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='nivelmeta',
            options={'verbose_name': 'Nível de Meta', 'verbose_name_plural': 'Níveis de Metas'},
        ),
        migrations.RemoveField(
            model_name='analista',
            name='metas_referencia',
        ),
        migrations.AlterField(
            model_name='nivelmeta',
            name='nome_periodo',
            field=models.CharField(help_text='Ex: Janeiro 2026', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='nivelmeta',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='metas.empresa'),
        ),
        migrations.AlterField(
            model_name='analista',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analistas', to='metas.empresa'),
        ),
    ]
