# Generated by Django 6.0.1 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0003_empresa_alter_nivelmeta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analistas', to='metas.empresa'),
        ),
    ]
