# Generated by Django 6.0.1 on 2026-01-24 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0004_alter_analista_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaGlobalEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField(default=1)),
                ('ano_referencia', models.IntegerField(default=2026)),
                ('bronze_global', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prata_global', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ouro_global', models.DecimalField(decimal_places=2, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_globais', to='metas.empresa')),
            ],
            options={
                'verbose_name': 'Meta Global da Empresa',
                'verbose_name_plural': 'Metas Globais das Empresas',
            },
        ),
    ]
