# Generated by Django 6.0.1 on 2026-01-24 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0005_metaglobalempresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaGlobalEmpresa',
            new_name='MetaGlobalEmpresaAdmin',
        ),
    ]
