# Generated by Django 6.0.1 on 2026-01-24 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0006_rename_metaglobalempresa_metaglobalempresaadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaGlobalEmpresaAdmin',
            new_name='MetaGlobalEmpresa',
        ),
    ]
