# Generated by Django 6.0.1 on 2026-01-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0007_rename_metaglobalempresaadmin_metaglobalempresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrecadacaodiaria',
            options={'verbose_name': 'Arrecadação Diária', 'verbose_name_plural': 'Arrecadações Diárias'},
        ),
        migrations.AlterModelOptions(
            name='nivelmeta',
            options={'verbose_name': 'Nível de Meta Individual', 'verbose_name_plural': 'Níveis de Metas Individuais'},
        ),
    ]
