# Generated by Django 6.0.1 on 2026-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0008_alter_arrecadacaodiaria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelmeta',
            options={'verbose_name': 'Nível de Meta Analista', 'verbose_name_plural': 'Níveis de Metas Analistas'},
        ),
        migrations.AlterField(
            model_name='metaglobalempresa',
            name='mes_referencia',
            field=models.IntegerField(default=2),
        ),
    ]
