# Generated by Django 6.0.1 on 2026-02-08 14:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0009_alter_nivelmeta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivelmeta',
            options={'verbose_name': 'Nível de Meta Sugerida', 'verbose_name_plural': 'Níveis de Metas Sugeridas'},
        ),
        migrations.AddField(
            model_name='analista',
            name='meta_individual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Defina a meta principal (Ouro) para este analista específico.', max_digits=12),
        ),
    ]
