# Generated by Django 6.0.1 on 2026-02-08 15:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metas', '0010_alter_nivelmeta_options_analista_meta_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analista',
            name='meta_individual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
